### ISSUE TITLE
Programming language to run

### ISSUE THREAD

**Issue by hfeltham-creator** [GCWizard/GCWizard#1996]
Could you consider doing different programming language decipers or to run the language if paste in. Such as python, etc

**Comment by t-m-z** [comment]
Hello Hayley, 
this is a rather good question and idea. 

Currently the GC Wizards supports two kind of programming languages:
- esoteric programming languages like Malbolge, Befunge, Beatnik, Brainf*ck, Chef etc. which were sometimes used to encrypt coordinates and so on
- a BASIC kind of a scripting language to assist cachers for doing calculations to get coordinates.

Both types have in common that they do not rely on libraries like jar-files or py-modules etc. To allow the usage of libraries it is necessary to implement all the function calls which are provided through those libraries.

Hence I believe it is not feasible to implement due to all the existing libraries for the different programming languages.
I am sorry - but your idea will go far beyond the scope of the GC Wizard App.

**Comment by t-m-z** [comment]
Nice idea - but providing a general interpreter for different programming languages is far beyond the scop of the app

**Comment by t-m-z** [comment]
Nice idea - but providing a general interpreter for different programming languages is far beyond the scop of the app

**Comment by t-m-z** [comment]
Nice idea - but providing a general interpreter for different programming languages is far beyond the scop of the app

**Comment by t-m-z** [comment]
Nice idea - but providing a general interpreter for different programming languages is far beyond the scop of the app
